### ISSUE TITLE
periodic tasks stopped working

### ISSUE THREAD

**Issue by SiddiqueAhmad** [evantahler/actionhero#686] opened 2015-10-06 09:10 UTC
periodic tasks stopped working, could not find any reason, normal task are working okay, any clue

**Comment by evantahler** [comment] 2015-10-06 15:52
We'll need a lot more information to help (and probably a reproducible example)
- what version of actionhero are you using?
- what version of redis?
- what OS
- Is the scheduler enabled? 
- Look in redis. Are there jobs in the delayed queue?

**Comment by evantahler** [comment] 2015-11-25 17:20
closing due to silence

**Closed by evantahler** 2015-11-25 17:20 UTC
Labels: User Error / User Implementation, Waiting On Poster

**Comment by hazemhagrass** [comment] 2016-12-01 12:24
@evantahler I have the same issue, periodic tasks stopped working suddenly

**Comment by evantahler** [comment] 2016-12-01 18:14
@hazemhagrass you'll need to answer those questions above for anyone to provide assistance

**Comment by hazemhagrass** [comment] 2016-12-02 23:20
what version of actionhero are you using?
15.3.0

what version of redis?
3.2

what OS?
Ubuntu 16.04

Is the scheduler enabled?
Yes

Look in redis. Are there jobs in the delayed queue?
Yes

**Comment by evantahler** [comment] 2016-12-02 23:35
one of 2 things is likely happening:
- your job has `hung`.  This means that the job never completed its callback and has been "running" for a very long time.  Look in redis and see if a worker has been working on this specific job for a while
- your job has crashed. Look in the resque error queue for the crashed job, and see what the stack trace was

**Comment by hazemhagrass** [comment] 2016-12-02 23:38
Will check them then back to you.
Do you recommend any dashboard view for actionhero platform to monitor logs, queues and redis?

**Comment by evantahler** [comment] 2016-12-03 00:16
There's this: https://github.com/evantahler/ah-resque-ui, but actionhero lets you configure things very openly, so the monitoring tool you need might not be the same as another implementation.  There are plugins for datadog, new-relic, logly, etc

**Comment by hazemhagrass** [comment] 2016-12-03 04:18
@evantahler Many thanks. your tool is perfect. I will monitor all delayed tasks and locks then let you know. thanks a lot for your help.

**Comment by hazemhagrass** [comment] 2016-12-03 14:28
@evantahler see this is my case
![screen shot 2016-12-03 at 4 29 32 pm](https://cloud.githubusercontent.com/assets/3625423/20859938/705e5f74-b975-11e6-86e7-58055595001a.png)
![screen shot 2016-12-03 at 4 29 37 pm](https://cloud.githubusercontent.com/assets/3625423/20859934/700348dc-b975-11e6-9736-cf45b7e1f4ca.png)
![screen shot 2016-12-03 at 4 29 42 pm](https://cloud.githubusercontent.com/assets/3625423/20859935/702c9228-b975-11e6-8885-35a0bb7107fc.png)
![screen shot 2016-12-03 at 4 29 44 pm](https://cloud.githubusercontent.com/assets/3625423/20859936/7032ff82-b975-11e6-9027-e6a56482816a.png)
![screen shot 2016-12-03 at 4 29 47 pm](https://cloud.githubusercontent.com/assets/3625423/20859937/70342218-b975-11e6-919e-7033f47eb65e.png)

**Comment by evantahler** [comment] 2016-12-03 19:10
everything looks fine to me... you've got a worker, some jobs which will run in the future... 
so what's wrong?

**Comment by hazemhagrass** [comment] 2016-12-04 10:11
Yes you are right, it's my fault, anyway it's working now, I will keep tracking it.
