### ISSUE TITLE
cpu usage up to 100%

### ISSUE THREAD

**Issue by enginespot** [evantahler/actionhero#635] opened 2015-04-15 03:13 UTC
I deploy api server to production server ,and then run a command like

..\node_modules\actionhero\bin\actionhero startCluster

after for a while , the cpu usage up to 100% , I am not sure where is wrong , so can you give me some idea , how to check it .

Thanks.

 7594 root      20   0 1139m 245m 7396 R  100  6.6  27:53.76 nodejs
 7588 root      20   0 1133m 237m 7380 R   99  6.4  27:42.24 nodejs

actionhero version :9.4.1

**Comment by evantahler** [comment] 2015-04-15 09:23
You are going to need to provide a lot more information:

- tell us about the machine: CPU/RAM/DISK/OS, etc
- Is the CLUSTER or the WORKERS using up the CPU?
- how many workers are you running?
- can you still serve requests while the CPU is pegged?
- what type of connections (web, websocket, etc)
- how many connections?
- what do the logs say?

Either way, you'll need to use a *lot* of logging (with timing data) to sort out these types of problems.  Could be an action has a double-callback, could be that you just have a lot of traffic (for the host you are running on).  It also might be that you found a bug!  However, we'll need to be able to reproduce it to fix it.

In my experience, the biggest reason for this type of behavior in node is garbage collection... caused by the allocation of a great many objects.  There are a lot of good articles out there about debugging node memory leaks, like this one https://strongloop.com/strongblog/node-js-performance-tip-of-the-week-memory-leak-diagnosis

I'm closing this issue, as it is vauge.  If you need advice, head over to the [mailing list](https://groups.google.com/forum/#!forum/actionhero-js).  If you find a big, please open up a new issue!

**Closed by evantahler** 2015-04-15 09:24 UTC

**Comment by enginespot** [comment] 2015-04-17 03:01
I find what's wrong with my code 

it is a file server , code like:


if user send a request like 
http://api.web.com/abc.png and for the file exist in the directory '/tmp/uploads' , it will get response 

but if user send a request like
http://api.web.com/asdfghjk.png , but for the file does not exist , the follow code will run
```
connection.rawConnection.responseHttpCode = 404; 
connection.sendFile('404.html');
next(connection, false);
```
but , the problem is that for 404.html , it does not exist in the /tmp/uploads , so the above called again and again.

then cpu up to 100%

**Comment by evantahler** [comment] 2015-04-17 11:46
Glad you fixed it!  However, trying to return a file that doesn't exist sholdn't cause any higher CPU load than normal... unless your server is constantly crashing and restarting... is that the case?

**Comment by enginespot** [comment] 2015-04-17 13:13
Hmm...

I think the default workflow like the follows:

for server side , if we want to return 404 , we can call a default function (action) , and for the default function we can also custom it .

btw , currently our team use actionhero 9.4.1 , since that the logic of "action" has some difference with version 10 , and also for our team , we use coffeescript (compile it to js auto) as our main nodejs language , so by now , we did not upgrade it
