### ISSUE TITLE
README links need to be updated

### ISSUE THREAD

**Issue by crazy4groovy** [evantahler/actionhero#707] opened 2015-11-25 14:41 UTC
Eg. wrong: http://actionherojs.com/docs/ops/getting-started.html --> correct: http://www.actionherojs.com/docs/#getting-started

**Comment by evantahler** [comment] 2015-11-25 17:16
duplicate of https://github.com/evantahler/actionhero/pull/706/

**Closed by evantahler** 2015-11-25 17:16 UTC

**Comment by slattery** [comment] 2015-11-27 02:06
Hmmm, the README.md needs work too, new PR incoming, sorry about the gh-pages mixup last time...

**Comment by evantahler** [comment] 2015-11-27 18:09
solved by https://github.com/evantahler/actionhero/pull/710
